export const translations = {
  en: {
    chronicDiseases: "Chronic Diseases",
    diseases: "Diseases",
    date: "Date",
    diagnosis: "Diagnosis",
    clinic: "Clinic",
    doctor: "Doctor",
    action: "Action",
    details: "Details",
    pageTitle: "Recipes",
    prescriptionDetails: "Prescription Details",
    medicine: "Medicine",
    usage: "Usage",
    testTitle: "Tests",
    testName: "Test Name",
    result: "Result",
    upcomingVisits: "Upcoming visits",
    showAll: "Show All Hospitals",
    sortBy: "Sort By",
    name: "Name",
    addedDate: "Added Date",
    bloodTest: "Blood Test",
    xRay: "X-ray",
    ctScan: "CT Scan",
    mri: "MRI",
    ultrasound: "Ultrasound",
    positive: "Positive",
    negative: "Negative",
    rasimQulamov: "Rasim Qulamov",
    turkanIsmayilova: "Türkan İsmayılova",
    telmanYusifov: "Telman Yusifov",
    arifOrucov: "Arif Orucov",
    saminQulamov: "Samin Qulamov",
    // Login Data
    home: "Home",
    loginTitle: "Log In",
    idLabel: "Identification number",
    passwordLabel: "Password",
    rememberMe: "Remember Me",
    forgotPassword: "Forgot Password",
    signIn: "Sign In",
    digitalLogin: "Sign in with Digital Login",
    signUp: "Don’t have an account? Sign up",
    sima: "SİMA Digital Signature",
    asan: "Asan Signature",
    token: "SİMA Token (Electronic Signature)",
    bsxm: "BSXM Electronic Signature",
    // Register Data
    registerTitle: "Sign Up",
    fullName: "Full Name",
    dob: "Date of Birth",
    gender: "Gender",
    genderSelect: "Select Gender",
    female: "Female",
    male: "Male",
    other: "Prefer Not to Say",
    id: "National ID / Passport Number",
    phone: "Phone Number",
    email: "Email",
    address: "Residential Address",
    register: "Register",
    alreadyAccount: "Already have an account? ",
    signIn: "Sign in",  
  },
  az: {
    chronicDiseases: "Xroniki Xəstəliklər",
    diseases: "Xəstəliklər",
    date: "Tarix",
    diagnosis: "Diaqnoz",
    clinic: "Klinika",
    doctor: "Həkim",
    action: "Əməliyyat",
    details: "Ətraflı",
    pageTitle: "Reseptlər",
    prescriptionDetails: "Rəseptin Detalları",
    medicine: "Dərman",
    usage: "İstifadə",
    testTitle: "Testlər",
    testName: "Test Adı",
    result: "Nəticə",
    upcomingVisits: "Yaxın Ziyarətlər",
    showAll: "Bütün Xəstəxanaları Göstər",
    sortBy: "Sıralama",
    name: "Ad",
    addedDate: "Əlavə Edilən Tarix",
    bloodTest: "Qan testi",
    xRay: "Rentgen",
    ctScan: "CT Skani",
    mri: "MRT",
    ultrasound: "Ultrasəs",
    positive: "Müsbət",
    negative: "Mənfi",
    rasimQulamov: "Rasim Qulamov",
    turkanIsmayilova: "Türkan İsmayılova",
    telmanYusifov: "Telman Yusifov",
    arifOrucov: "Arif Orucov",
    saminQulamov: "Samin Qulamov",
    // Login Data
    home: "Əsas Səhifə",
    loginTitle: "Daxil ol",
    idLabel: "Şəxsiyyət vəsiqəsi nömrəsi",
    passwordLabel: "Şifrə",
    rememberMe: "Məni yadda saxla",
    forgotPassword: "Şifrəni unutdunuz?",
    signIn: "Daxil ol",
    digitalLogin: "Rəqəmsal İmza ilə daxil ol",
    signUp: "Hesabınız yoxdursa? Qeydiyyatdan keçin",
    sima: "SİMA Rəqəmsal İmza",
    asan: "Asan İmza",
    token: "SİMA Token (Elektron İmza)",
    bsxm: "BSXM Elektron İmza",
    // Register Data
    registerTitle: "Qeydiyyatdan Keç",
    fullName: "Ad Soyad",
    dob: "Doğum Tarixi",
    gender: "Cinsiyyət",
    genderSelect: "Cinsiyyəti Seçin",
    female: "Qadın",
    male: "Kişi",
    other: "Demək İstəmədim",
    id: "Şəxsiyyət vəsiqəsi / Pasport Nömrəsi",
    phone: "Telefon Nömrəsi",
    email: "E-poçt",
    address: "Yaşayış Ünvanı",
    register: "Qeydiyyat",
    alreadyAccount: "Hesabınız var? ",
    signIn: "Daxil ol",
  },
  rus: {
    chronicDiseases: "Хронические болезни",
    diseases: "Болезни",
    date: "Дата",
    diagnosis: "Диагноз",
    clinic: "Клиника",
    doctor: "Доктор",
    action: "Действие",
    details: "Детали",
    pageTitle: "Pецепты",
    prescriptionDetails: "Детали рецепта",
    medicine: "Лекарство",
    usage: "Использование",
    testTitle: "Тесты",
    testName: "Название теста",
    result: "Результат",
    upcomingVisits: "Предстоящие визиты",
    showAll: "Показать все больницы",
    sortBy: "Сортировать по",
    name: "Имя",
    addedDate: "Дата добавления",
    bloodTest: "Анализ крови",
    xRay: "Рентген",
    ctScan: "КТ сканирование",
    mri: "МРТ",
    ultrasound: "УЗИ",
    positive: "Положительный",
    negative: "Отрицательный",
    rasimQulamov: "Расим Гуланов",
    turkanIsmayilova: "Тюркан Исмайлова",
    telmanYusifov: "Телман Юсифов",
    arifOrucov: "Ариф Орджов",
    saminQulamov: "Самин Гуланов",
    // Login Data
    home: "Домой",
    loginTitle: "Войти",
    idLabel: "Идентификационный номер",
    passwordLabel: "Пароль",
    rememberMe: "Запомнить меня",
    forgotPassword: "Забыли пароль",
    signIn: "Войти",
    digitalLogin: "Войти с помощью цифровой подписи",
    signUp: "Нет аккаунта? Зарегистрироваться",
    sima: "Цифровая подпись СИМА",
    asan: "Подпись Asan",
    token: "Токен СИМА (Электронная подпись)",
    bsxm: "Электронная подпись BSXM",
     // Register Data
     registerTitle: "Регистрация",
     fullName: "Полное имя",
     dob: "Дата Рождения",
     gender: "Пол",
     genderSelect: "Выберите Пол",
     female: "Женский",
     male: "Мужской",
     other: "Предпочитаю не говорить",
     id: "Национальный ID / Номер Паспорта",
     phone: "Номер Телефона",
     email: "Электронная почта",
     address: "Домашний Адрес",
     register: "Регистрация",
     alreadyAccount: "Уже есть аккаунт? ",
     signIn: "Войти",
  },
};


// Diseases
export const diseasesData = {
  "17-03-2025": {
    en: {
      diagnosis: "Type 2 Diabetes",
      clinic: "Shafa Clinic",
      doctor: "Nigar Hasanova",
    },
    az: {
      diagnosis: "2-ci Tip Şəkərli Diabet",
      clinic: "Şəfa Klinika",
      doctor: "Nigar Hasanova",
    },
    rus: {
      diagnosis: "Диабет 2 типа",
      clinic: "Клиника Шафа",
      doctor: "Нигар Хасановa",
    },
  },
  "08-03-2025": {
    en: {
      diagnosis: "Hypertension",
      clinic: "Medical Center 2020",
      doctor: "Elchin Mammadov",
    },
    az: {
      diagnosis: "Hipertenziya",
      clinic: "Medical Center 2020",
      doctor: "Elçin Məmmədov",
    },
    rus: {
      diagnosis: "Гипертония",
      clinic: "Медицинский центр 2020",
      doctor: "Эльчин Мамедов",
    },
  },
  "20-02-2025": {
    en: {
      diagnosis: "Asthma",
      clinic: "Ganja Health House",
      doctor: "Rauf Aliyev",
    },
    az: {
      diagnosis: "Astma",
      clinic: "Gəncə Sağlamlıq Evi",
      doctor: "Rauf Əliyev",
    },
    rus: {
      diagnosis: "Астма",
      clinic: "Гянджа Медицинский дом",
      doctor: "Рафаэль Алиев",
    },
  },
  "05-02-2025": {
    en: {
      diagnosis: "Rheumatoid Arthritis",
      clinic: "Baku Medical Center",
      doctor: "Leman Guliyeva",
    },
    az: {
      diagnosis: "Revmatoid Artrit",
      clinic: "Bakı Tibb Mərkəzi",
      doctor: "Ləman Quliyeva",
    },
    rus: {
      diagnosis: "Ревматоидный артрит",
      clinic: "Баку Медицинский Центр",
      doctor: "Лейман Гулиева",
    },
  },
  "28-01-2025": {
    en: {
      diagnosis: "Chronic Kidney Disease",
      clinic: "Healthy Breath Clinic",
      doctor: "Kamran Abbasov",
    },
    az: {
      diagnosis: "Xroniki Böyrək Xəstəliyi",
      clinic: "Healthy Breath Clinic",
      doctor: "Kamran Abbasov",
    },
    rus: {
      diagnosis: "Хроническая болезнь почек",
      clinic: "Клиника Здорового дыхания",
      doctor: "Камран Аббасов",
    },
  },
};

//Receipts

export const receiptsData = [
  {
    date: "23-04-2025",
    clinic: {en: "Ege Hospital", az: "Ege Hospital", rus: "Еге Госпиталь" },
    doctor: { en: "Huseyn Aliyev", az: "Hüseyn Əliyev", rus: "Хусейн Алиев" },
    prescription: [
      {
        medicine: {
          en: "Paracetamol",
          az: "Paratsetamol",
          rus: "Парацетамол",
        },
        usage: {
          en: "Twice a day after meals",
          az: "Hər gün yeməkdən sonra iki dəfə",
          rus: "Дважды в день после еды",
        },
      },
      {
        medicine: { en: "Ibuprofen", az: "İbuprofen", rus: "Ибупрофен" },
        usage: {
          en: "Once a day",
          az: "Hər gün bir dəfə",
          rus: "Один раз в день",
        },
      },
    ],
  },
  {
    date: "22-04-2025",
    clinic: {en: "Referance Hospital", az: "Referance Hospital", rus: "Референс Госпиталь" },
    doctor: { en: "Arif Orucov", az: "Arif Orucov", rus: "Ариф Орджов" },
    prescription: [
      {
        medicine: { en: "Xanax", az: "Zanaks", rus: "Ксанакс" },
        usage: {
          en: "Once a day at bedtime",
          az: "Hər gün yatmazdan əvvəl bir dəfə",
          rus: "Один раз в день перед сном",
        },
      },
      {
        medicine: {
          en: "Amoxicillin",
          az: "Amoksisillin",
          rus: "Амоксициллин",
        },
        usage: {
          en: "Twice a day",
          az: "Gündə iki dəfə",
          rus: "Дважды в день",
        },
      },
    ],
  },
  {
    date: "21-04-2025",
    clinic: {en: "Baku Medical Plaza", az: "Baku Medical Plaza", rus: "Баку Мед Плаза" },
    doctor: {
      en: "Telman Yusifov",
      az: "Telman Yusifov",
      rus: "Телман Юсифов",
    },
    prescription: [
      {
        medicine: {
          en: "Ciprofloxacin",
          az: "Ciprofloksasin",
          rus: "Ципрофлоксацин",
        },
        usage: {
          en: "Every 12 hours",
          az: "Hər 12 saatda",
          rus: "Каждые 12 часов",
        },
      },
      {
        medicine: { en: "Aspirin", az: "Aspirin", rus: "Аспирин" },
        usage: {
          en: "Once a day",
          az: "Hər gün bir dəfə",
          rus: "Один раз в день",
        },
      },
    ],
  },
  {
    date: "20-04-2025",
    clinic: {en: "West Hospital", az: "West Hospital", rus: "Западная больница" },
    doctor: {
      en: "Kazim Qasimov",
      az: "Kazım Qasımov",
      rus: "Казим Касымов",
    },
    prescription: [
      {
        medicine: { en: "Omeprazole", az: "Omeprazol", rus: "Омепразол" },
        usage: {
          en: "Before meals",
          az: "Yeməkdən əvvəl",
          rus: "Перед едой",
        },
      },
      {
        medicine: {
          en: "Folic acid",
          az: "Fol turşusu",
          rus: "Фолиевая кислота",
        },
        usage: {
          en: "Once a day",
          az: "Hər gün bir dəfə",
          rus: "Один раз в день",
        },
      },
    ],
  },
  {
    date: "19-04-2025",
    clinic: {en: "MedEra Hospital", az: "MedEra Hospital", rus: "МедЭра Госпиталь" },
    doctor: {
      en: "Aysel Aliyeva",
      az: "Aysel Əliyeva",
      rus: "Айсель Алиева",
    },
    prescription: [
      {
        medicine: {
          en: "Paracetamol",
          az: "Paratsetamol",
          rus: "Парацетамол",
        },
        usage: {
          en: "Twice a day after meals",
          az: "Hər gün yeməkdən sonra iki dəfə",
          rus: "Дважды в день после еды",
        },
      },
      {
        medicine: {
          en: "Amoxicillin",
          az: "Amoksisillin",
          rus: "Амоксициллин",
        },
        usage: {
          en: "Every 8 hours",
          az: "Hər 8 saatda",
          rus: "Каждые 8 часов",
        },
      },
    ],
  },
];


//Tests
export const testData = [
  {
    date: "23-04-2025",
    testName: { en: "Blood Test", az: "Qan testi", rus: "Анализ крови" },
    result: { en: "Positive", az: "Müsbət", rus: "Положительный" },
    clinic: { en: "Baku Medical Plaza", az: "Bakı Tibb Mərkəzi", rus: "Баку Медицинский Плаза" },
    doctor: { en: "Rasim Qulamov", az: "Rasim Qulamov", rus: "Расим Гуланов" },
  },
  {
    date: "22-04-2025",
    testName: { en: "X-ray", az: "Rentgen", rus: "Рентген" },
    result: { en: "Negative", az: "Mənfi", rus: "Отрицательный" },
    clinic: { en: "Referance Hospital", az: "Referans Xəstəxanası", rus: "Референтная больница" },
    doctor: { en: "Türkan İsmayılova", az: "Türkan İsmayılova", rus: "Тюркан Исмайлова" },
  },
  {
    date: "21-04-2025",
    testName: { en: "CT Scan", az: "CT Skani", rus: "КТ сканирование" },
    result: { en: "Positive", az: "Müsbət", rus: "Положительный" },
    clinic: { en: "Ege Hospital", az: "Ege Xəstəxanası", rus: "Еге Госпиталь" },
    doctor: { en: "Telman Yusifov", az: "Telman Yusifov", rus: "Телман Юсифов" },
  },
  {
    date: "20-04-2025",
    testName: { en: "MRI", az: "MRT", rus: "МРТ" },
    result: { en: "Negative", az: "Mənfi", rus: "Отрицательный" },
    clinic: { en: "Baku Medical Plaza", az: "Bakı Tibb Mərkəzi", rus: "Баку Медицинский Плаза" },
    doctor: { en: "Arif Orucov", az: "Arif Orucov", rus: "Ариф Орджов" },
  },
  {
    date: "19-04-2025",
    testName: { en: "Ultrasound", az: "Ultrasəs", rus: "УЗИ" },
    result: { en: "Positive", az: "Müsbət", rus: "Положительный" },
    clinic: { en: "Baku Medical Plaza", az: "Bakı Tibb Mərkəzi", rus: "Баку Медицинский Плаза" },
    doctor: { en: "Samin Qulamov", az: "Samin Qulamov", rus: "Самин Гуланов" },
  },
];


//Visited Hospitals
export const hospitalData = [
  {
    id: 1,
    clinicLogo:"E",
    name: "Ege Hospital",
    adress: "38 Academician Hasan Aliyev St",
    dateTime: "19 january, 08:00",
    doctorName: {
      en: "Huseyn Aliyev",
      az: "Hüseyn Əliyev",
      rus: "Хусейн Алиев",
    },
    profession: {
      en: "Dentist",
      az: "Diş Həkimi",
      rus: "Стоматолог",
    },
    picture: "https://sp-ao.shortpixel.ai/client/to_webp,q_glossy,ret_img/https://yellowpages.az/wp-content/uploads/2020/06/Logo-1.png",
    prescription: [
      { medicine: { en: "Paracetamol", az: "Paratsetamol", rus: "Парацетамол" }, usage: { en: "Twice a day after meals", az: "Hər gün yeməkdən sonra iki dəfə", rus: "Дважды в день после еды" } },
      { medicine: { en: "Ibuprofen", az: "İbuprofen", rus: "Ибупрофен" }, usage: { en: "Once a day", az: "Hər gün bir dəfə", rus: "Один раз в день" } },
    ],
    visible: true,
  },
  {
    id: 2,
    name: "Referance Hospital",
    clinicLogo:"R",
    adress: "Matbuat Street 35A",
    dateTime: "3 february, 13:00",
    doctorName: {
      en: "Arif Orucov",
      az: "Arif Orucov",
      rus: "Ариф Орджов",
    },
    profession: {
      en: "Ophthalmologist",
      az: "Oftalmoloq",
      rus: "Офтальмолог",
    },
    picture: "https://referansclc.az/upload/CAllcorp3Medc/e80/rigiwv18teqc4eqvtnjbvfqw1126q1cv.png",
    prescription: [
      { medicine: { en: "Xanax", az: "Zanaks", rus: "Ксанакс" }, usage: { en: "Once a day at bedtime", az: "Hər gün yatmazdan əvvəl bir dəfə", rus: "Один раз в день перед сном" } },
      { medicine: { en: "Amoxicillin", az: "Amoksisillin", rus: "Амоксициллин" }, usage: { en: "Twice a day", az: "Gündə iki dəfə", rus: "Дважды в день" } },
    ],
    visible: true,
  },
  {
    id: 3,
    clinicLogo:"BM",
    name: "Baku Medical Plaza",
    adress: "Babak avenue 42N",
    dateTime: "15 february, 14:00",
    doctorName: {
      en: "Telman Yusifov",
      az: "Telman Yusifov",
      rus: "Телман Юсифов",
    },
    profession: {
      en: "Dermatologist",
      az: "Dərmatoloq",
      rus: "Дерматолог",
    },
    picture: "https://www.bmp.az/assets/bmplogo-CCNYgYXy.svg",
    prescription: [
      { medicine: { en: "Ciprofloxacin", az: "Ciprofloksasin", rus: "Ципрофлоксацин" }, usage: { en: "Every 12 hours", az: "Hər 12 saatda", rus: "Каждые 12 часов" } },
      { medicine: { en: "Aspirin", az: "Aspirin", rus: "Аспирин" }, usage: { en: "Once a day", az: "Hər gün bir dəfə", rus: "Один раз в день" } },
    ],
    visible: true,
  },
];


//User Profile
export const userProfileData = {
  en: {
    name: "Rauf Khudiyev",
    ageLabel: "Age:",
    sexLabel: "Gender:",
    weightLabel: "Weight:",
    heightLabel: "Height:",
    age: "22",
    gender: "Male",
    weight: "76 kg",
    height: "182 cm",
    upcomingVisits: [
      { hospitalLetter: "E", hospital: "Ege Hospital", doctor: "Huseyn Aliyev, Dentistry", dateTime: "19 January, 08:00" },
      { hospitalLetter: "R", hospital: "Referance Hospital", doctor: "Arif Orucov, Ophthalmology", dateTime: "3 February, 13:00" },
      { hospitalLetter: "BM", hospital: "Baku Medical Plaza", doctor: "Telman Yusifov, Dermatology", dateTime: "15 February, 14:00" },
    ],
  },
  az: {
    name: "Rauf Xudiyev",
    ageLabel: "Yaş:",
    sexLabel: "Cins:",
    weightLabel: "Çəki:",
    heightLabel: "Boy:",
    age: "22",
    gender: "Kişi",
    weight: "76 kg",
    height: "182 sm",
    upcomingVisits: [
      { hospitalLetter: "E", hospital: "Ege Xəstəxanası", doctor: "Hüseyn Əliyev, Diş Həkimi", dateTime: "19 yanvar, 08:00" },
      { hospitalLetter: "R", hospital: "Referans Xəstəxanası", doctor: "Arif Orucov, Oftalmoloq", dateTime: "3 fevral, 13:00" },
      { hospitalLetter: "BM", hospital: "Bakı Tibb Plaza", doctor: "Telman Yusifov, Dermatoloq", dateTime: "15 fevral, 14:00" },
    ],
  },
  rus: {
    name: "Раоф Худиев",
    ageLabel: "Возраст:",
    sexLabel: "Пол:",
    weightLabel: "Вес:",
    heightLabel: "Рост:",
    age: "22",
    gender: "Мужчина",
    weight: "76 кг",
    height: "182 см",
    upcomingVisits: [
      { hospitalLetter: "E", hospital: "Еге Госпиталь", doctor: "Хусейн Алиев, Стоматолог", dateTime: "19 января, 08:00" },
      { hospitalLetter: "R", hospital: "Референс Госпиталь", doctor: "Ариф Орджов, Офтальмолог", dateTime: "3 февраля, 13:00" },
      { hospitalLetter: "BM", hospital: "Баку Мед Плаза", doctor: "Телман Юсифов, Дерматолог", dateTime: "15 февраля, 14:00" },
    ],
  },
};

